fix ValueError exception when no disks are detected in the disk menu (#4598)
* Fix ValueError exception when no disks are detected in the disk menu

in lib/disk/disk_menu.py, the menu items are created using info from a list called "devices" (device_handler.devices). when no block devices are detected, the list is empty, creating zero MenuItems, and causing the following ValueError:

ValueError: Menu must have at least one item

this change checks if the length of the list is shorter than 1  (empty list) before constructing the menu. if the list is empty, the user will be notified that no disks were detected. otherwise, the menu is created and behaves as normal

* Fixed ruff formatting issue

* Fixed ruff formatting issue

---------

Co-authored-by: Anton Hvornum <torxed@archlinux.org>